name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  build:
    name: Build in Java17
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - run: chmod +x ./gradlew
      - run: ./gradlew build
