name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag'
        required: true
        default: 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: |
            org.opencontainers.image.source = https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.actor }}/citation:latest
            ghcr.io/${{ github.actor }}/citation:${{ github.event.inputs.version }}
