name: trivy scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build citation Docker Image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build image from Dockerfile
        run: |
          docker build ./ -t citation

  scan:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-22.04

    steps:
      - name: Scan image
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: citation
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Send report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
